# -*- python -*-
#
# $Header$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: genericSources-01-12-00

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

if baseEnv['PLATFORM'] != 'win32':
    progEnv.AppendUnique(CPPDEFINES = ['TRAP_FPE'])

libEnv.Tool('genericSourcesLib', depsOnly = 1)
genericSourcesLib = libEnv.StaticLibrary('genericSources',
                                         listFiles(['src/*.cxx', 'src/*.c']))

progEnv.Tool('genericSourcesLib')

test_genericSourcesBin = progEnv.Program('test_genericSources',
                                         'src/test/test.cxx')

progEnv.Tool('registerObjects', package='genericSources', 
             libraries=[genericSourcesLib],
             includes=listFiles(['genericSources/*.h']),
             testApps=[test_genericSourcesBin],
             data = listFiles(['data/*'], recursive = True),
             xml = listFiles(['xml/*'], recursive = True))
