# -*- python -*-
#
# $Header$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: genericSources-01-14-02

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('genericSourcesLib', depsOnly = 1)
genericSourcesLib = libEnv.StaticLibrary('genericSources',
                                         listFiles(['src/*.cxx', 'src/*.c']))

progEnv.Tool('genericSourcesLib')

test_genericSourcesBin = progEnv.Program('test_genericSources',
                                         'src/test/test.cxx')

progEnv.Tool('registerTargets', package='genericSources', 
             staticLibraryCxts=[[genericSourcesLib, libEnv]],
             includes=listFiles(['genericSources/*.h']),
             testAppCxts=[[test_genericSourcesBin, progEnv]],
             data = listFiles(['data/*'], recursive = True),
             xml = listFiles(['xml/*'], recursive = True))
