# -*- python -*-
# $Id$
# Authors: Keith Bechtol<bechtol@stanford.edu>, Luigi Tibaldo
# <luigi.tibaldo@mpi-hd.mpg.de>, Warit Mitthumsiri <mwarit@hotmail.com>
# Version: EarthPhenom-00-02-07
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('addLinkDeps', package = 'EarthPhenom', toBuild='static')
EarthPhenomLib = libEnv.StaticLibrary('EarthPhenom', listFiles(['src/*.cxx']))

progEnv.Tool('EarthPhenomLib')
test_EarthPhenom = progEnv.Program('test_EarthPhenom',
                                   listFiles(['src/test/*.cxx']))

progEnv.Tool('registerTargets', package = 'EarthPhenom',
             staticLibraryCxts = [[EarthPhenomLib, libEnv]],
             includes = listFiles(['EarthPhenom/*.h']),
             testAppCxts = [[test_EarthPhenom, progEnv]],
             xml = listFiles(['xml/*'], recursive = True))
