CMTrelease=14
cmt_hardware_query_command=uname -m
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/data0/glast/ScienceTools/InstallArea/rh9_gcc32/bin:/data0/glast/GRBSimul/InstallArea/rh9_gcc32/bin:/data0/glast/GRBSimul/celestialSources/InstallArea/rh9_gcc32/bin:${CMTROOT}/${CMTBIN}:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/matpack/bin:/data0/glast/extlib/ruby/bin:/home/users/omodei/glast/scripts:/home/users/omodei/VRVS2/Sharing_Server:/home/users/omodei/SN50E/bin:/home/users/omodei/bin:/home/users/omodei/bin/bin:/data0/glast/lheasoft/Linux_2.2_i686/bin:/data0/glast/lheasoft/Linux_2.2_i686/scripts:/data0/glast/lheasoft/Linux_2.2_i686/bin:/home/users/omodei/bin:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/matpack/bin:/data0/glast/extlib/ruby/bin:/home/users/omodei/glast/scripts:/home/users/omodei/VRVS2/Sharing_Server:/home/users/omodei/SN50E/bin:/home/users/omodei/bin:/home/users/omodei/bin/bin:/data0/glast/FITS_ROOT/bin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:${ROOTSYS}/bin
CLASSPATH=/data0/glast/ScienceTools/InstallArea/share/bin:/data0/glast/ScienceTools/InstallArea/share/lib:/data0/glast/GRBSimul/InstallArea/share/bin:/data0/glast/GRBSimul/InstallArea/share/lib:/data0/glast/GRBSimul/celestialSources/InstallArea/share/bin:/data0/glast/GRBSimul/celestialSources/InstallArea/share/lib::${CMTROOT}/java
debug_option=-g
cc=gcc
cdebugflags=$(debug_option)
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppdebugflags=$(debug_option)
cppflags=-pipe -ansi -W -Wall  -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppoptions) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic  $(linkdebug)
cpplink=$(cpp)   $(cpplinkflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
tags=$(CMTEXTRATAGS)
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_install_area_command=ln -s 
cmt_uninstall_area_command=/bin/rm -f 
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
NEWCMTCONFIG=i686-rh9-gcc32
GlastMain=${GLASTPOLICYROOT}/src/GlastMain.cxx
TestGlastMain=${GLASTPOLICYROOT}/src/TestGlastMain.cxx
BINDIR=rh9_gcc32
cppoptions=$(cppdebugflags_s)
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
linkdebug=-g 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC  -ldl 
libraryshr_linkopts=-fPIC -ldl 
EXTPACK_DIR=${GLAST_EXT}
XMLEXT_native_version=1.7.0
XMLEXT_DIR=${EXTPACK_DIR}/xerces/$(XMLEXT_native_version)
LD_LIBRARY_PATH=/data0/glast/ScienceTools/InstallArea/rh9_gcc32/lib:/data0/glast/GRBSimul/InstallArea/rh9_gcc32/lib:/data0/glast/GRBSimul/celestialSources/InstallArea/rh9_gcc32/lib::/lib:/usr/X11R6/lib:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/matpack/include:/data0/glast/lheasoft/Linux_2.2_i686/lib:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/cfitsio/v2470/lib:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/xerces/1.7.0/lib:/data0/glast/ScienceTools/xml/v4r11p2/${BINDIR}:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/CLHEP/1.8.0.0/lib:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/ROOT/v3.10.02/root/bin:/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/ROOT/v3.10.02/root/lib
XMLEXT_linkopts=-L$(XMLEXT_DIR)/lib/ -lxerces-c1_7_0 -lpthread
facilities_linkopts=-L${facilities_root}/${BINDIR} -lfacilities 
xml_linkopts=-L${xml_root}/${BINDIR} -lxml 
xml_shlibflags=$(libraryshr_linkopts)
xml_stamps=${XMLROOT}/${BINDIR}/xml.stamp 
CLHEP_native_version=1.8.0.0
CLHEP_DIR=$(GLAST_EXT)/CLHEP
CLHEPBASE=${CLHEP_DIR}/$(CLHEP_native_version)
CLHEP_linkopts=-L$(CLHEPBASE)/lib -lCLHEP
cfitsio_native_version=v2470
cfitsio_DIR=${GLAST_EXT}/cfitsio/$(cfitsio_native_version)
cfitsio_libs=-L${cfitsio_DIR}/lib -lcfitsio 
cfitsio_linkopts=$(cfitsio_libs) 
astro_linkopts=-L${astro_root}/${BINDIR} -lastro 
astro_stamps=${ASTROROOT}/${BINDIR}/astro.stamp 
flux_linkopts=-L${flux_root}/${BINDIR} -lflux 
flux_stamps=${FLUXROOT}/${BINDIR}/flux.stamp 
ROOT_DIR=${GLAST_EXT}/ROOT
ROOT_native_version=v3.10.02
ROOT_PATH=${ROOT_DIR}/$(ROOT_native_version)/root
ROOTSYS=/data0/glast/extlib/GlastRelease_v4_rh9_gcc32/ROOT/v3.10.02/root
dict=../dict/
rootcint=rootcint
ROOT_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lTree -lMatrix -lPhysics -lpthread -lm -ldl -rdynamic -lHist -lGraf  -lHist -lGraf  -lGpad 
ROOT_GUI_libs=-L$(ROOT_PATH)/lib -lHist -lGraf -lGraf3d -lGpad -lRint -lPostscript
ROOT_linkopts=$(ROOT_libs)
ROOT_cppflagsEx=$(ppcmd) "$(ROOT_PATH)/include" -DUSE_ROOT
ROOT_cppflags=-fpermissive
SpectObj_linkopts=-L${SpectObj_root}/${BINDIR} -lSpectObj 
GRBobs_linkopts=-L${GRBobs_root}/${BINDIR} -lGRBobs 
source=*.cxx
GlastPatternPolicyDir=${GLASTPATTERNPOLICYROOT}/${BINDIR}
GlastPolicyDir=${GLASTPOLICYROOT}/${BINDIR}
facilitiesDir=${FACILITIESROOT}/${BINDIR}
xmlDir=${XMLROOT}/${BINDIR}
astroDir=${ASTROROOT}/${BINDIR}
fluxDir=${FLUXROOT}/${BINDIR}
SpectObjDir=${SPECTOBJROOT}/${BINDIR}
GRBobsDir=${GRBOBSROOT}/${BINDIR}
CMTVERSION=v1r14p20031120
CMTINSTALLAREA=/data0/glast/GRBSimul/InstallArea
tag=rh9_gcc32
GRBobs_tag=$(tag)
GRBOBSROOT=/data0/glast/GRBSimul/celestialSources/GRBobs/v0
PACKAGE_ROOT=$(GRBOBSROOT)
GRBobs_root=../../../GRBobs/v0
GRBOBSVERSION=v0
srcdir=../src
bin=../$(GRBobs_tag)/
javabin=../classes/
mgrdir=cmt
GRBobs_cmtpath=/data0/glast/GRBSimul
GRBobs_offset=celestialSources
package_cmtpath=/data0/glast/GRBSimul
package_offset=celestialSources
version=v0
package=GRBobs
flux_tag=$(tag)
FLUXROOT=/data0/glast/ScienceTools/flux/v8r10p1
flux_root=/data0/glast/ScienceTools/flux/v8r10p1
FLUXVERSION=v8r10p1
flux_cmtpath=/data0/glast/ScienceTools
xml_tag=$(tag)
XMLROOT=/data0/glast/ScienceTools/xml/v4r11p2
xml_root=/data0/glast/ScienceTools/xml/v4r11p2
XMLVERSION=v4r11p2
xml_cmtpath=/data0/glast/ScienceTools
astro_tag=$(tag)
ASTROROOT=/data0/glast/ScienceTools/astro/v1r1p2
astro_root=/data0/glast/ScienceTools/astro/v1r1p2
ASTROVERSION=v1r1p2
astro_cmtpath=/data0/glast/ScienceTools
facilities_tag=$(tag)
FACILITIESROOT=/data0/glast/ScienceTools/facilities/v2r9p2
facilities_root=/data0/glast/ScienceTools/facilities/v2r9p2
FACILITIESVERSION=v2r9p2
facilities_cmtpath=/data0/glast/ScienceTools
SpectObj_tag=$(tag)
SPECTOBJROOT=/data0/glast/GRBSimul/celestialSources/SpectObj/v0
SpectObj_root=../../../SpectObj/v0
SPECTOBJVERSION=v0
SpectObj_cmtpath=/data0/glast/GRBSimul
SpectObj_offset=celestialSources
GlastPolicy_tag=$(tag)
GLASTPOLICYROOT=/data0/glast/ScienceTools/GlastPolicy/v6r3p4
GlastPolicy_root=/data0/glast/ScienceTools/GlastPolicy/v6r3p4
GLASTPOLICYVERSION=v6r3p4
GlastPolicy_cmtpath=/data0/glast/ScienceTools
GlastPatternPolicy_tag=$(tag)
GLASTPATTERNPOLICYROOT=/data0/glast/ScienceTools/GlastPolicy/GlastPatternPolicy/v0r1
GlastPatternPolicy_root=/data0/glast/ScienceTools/GlastPolicy/GlastPatternPolicy/v0r1
GLASTPATTERNPOLICYVERSION=v0r1
GlastPatternPolicy_cmtpath=/data0/glast/ScienceTools
GlastPatternPolicy_offset=GlastPolicy
GlastCppPolicy_tag=$(tag)
GLASTCPPPOLICYROOT=/data0/glast/ScienceTools/GlastPolicy/GlastCppPolicy/v0r2
GlastCppPolicy_root=/data0/glast/ScienceTools/GlastPolicy/GlastCppPolicy/v0r2
GLASTCPPPOLICYVERSION=v0r2
GlastCppPolicy_cmtpath=/data0/glast/ScienceTools
GlastCppPolicy_offset=GlastPolicy
XMLEXT_tag=$(tag)
XMLEXTROOT=/data0/glast/ScienceTools/IExternal/XMLEXT/v4r170p5
XMLEXT_root=/data0/glast/ScienceTools/IExternal/XMLEXT/v4r170p5
XMLEXTVERSION=v4r170p5
XMLEXT_cmtpath=/data0/glast/ScienceTools
XMLEXT_offset=IExternal
CLHEP_tag=$(tag)
CLHEPROOT=/data0/glast/ScienceTools/IExternal/CLHEP/v2r1800p5
CLHEP_root=/data0/glast/ScienceTools/IExternal/CLHEP/v2r1800p5
CLHEPVERSION=v2r1800p5
CLHEP_cmtpath=/data0/glast/ScienceTools
CLHEP_offset=IExternal
cfitsio_tag=$(tag)
CFITSIOROOT=/data0/glast/ScienceTools/IExternal/cfitsio/v1r2470p5
cfitsio_root=/data0/glast/ScienceTools/IExternal/cfitsio/v1r2470p5
CFITSIOVERSION=v1r2470p5
cfitsio_cmtpath=/data0/glast/ScienceTools
cfitsio_offset=IExternal
ROOT_tag=$(tag)
ROOTROOT=/data0/glast/ScienceTools/IExternal/ROOT/v2r31002p4
ROOT_root=/data0/glast/ScienceTools/IExternal/ROOT/v2r31002p4
ROOTVERSION=v2r31002p4
ROOT_cmtpath=/data0/glast/ScienceTools
ROOT_offset=IExternal
use_requirements=requirements $(CMTROOT)/mgr/requirements $(FLUXROOT)/cmt/requirements $(XMLROOT)/cmt/requirements $(ASTROROOT)/cmt/requirements $(FACILITIESROOT)/cmt/requirements $(SPECTOBJROOT)/cmt/requirements $(GLASTPOLICYROOT)/cmt/requirements $(GLASTPATTERNPOLICYROOT)/cmt/requirements $(GLASTCPPPOLICYROOT)/cmt/requirements $(XMLEXTROOT)/cmt/requirements $(CLHEPROOT)/cmt/requirements $(CFITSIOROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(FLUXROOT)" $(ppcmd)"$(XMLROOT)" $(ppcmd)"$(ASTROROOT)" $(ppcmd)"$(FACILITIESROOT)" $(ppcmd)"$(SPECTOBJROOT)" $(ppcmd)"$(XMLEXT_DIR)/include" $(ppcmd)"$(CLHEPBASE)/include" $(ppcmd)"${cfitsio_DIR}/include" $(ppcmd)"$(ROOT_PATH)/include" 
use_fincludes= $(use_includes)
use_stamps= $(GRBobs_stamps)  $(flux_stamps)  $(xml_stamps)  $(astro_stamps)  $(facilities_stamps)  $(SpectObj_stamps)  $(GlastPolicy_stamps)  $(GlastPatternPolicy_stamps)  $(GlastCppPolicy_stamps)  $(XMLEXT_stamps)  $(CLHEP_stamps)  $(cfitsio_stamps)  $(ROOT_stamps) 
use_cflags=  $(GRBobs_cflags)  $(flux_cflags)  $(xml_cflags)  $(astro_cflags)  $(facilities_cflags)  $(SpectObj_cflags)  $(GlastPolicy_cflags)  $(XMLEXT_cflags)  $(CLHEP_cflags)  $(cfitsio_cflags)  $(ROOT_cflags) 
use_pp_cflags=  $(GRBobs_pp_cflags)  $(flux_pp_cflags)  $(xml_pp_cflags)  $(astro_pp_cflags)  $(facilities_pp_cflags)  $(SpectObj_pp_cflags)  $(GlastPolicy_pp_cflags)  $(XMLEXT_pp_cflags)  $(CLHEP_pp_cflags)  $(cfitsio_pp_cflags)  $(ROOT_pp_cflags) 
use_cppflags=  $(GRBobs_cppflags)  $(flux_cppflags)  $(xml_cppflags)  $(astro_cppflags)  $(facilities_cppflags)  $(SpectObj_cppflags)  $(GlastPolicy_cppflags)  $(XMLEXT_cppflags)  $(CLHEP_cppflags)  $(cfitsio_cppflags)  $(ROOT_cppflags) 
use_pp_cppflags=  $(GRBobs_pp_cppflags)  $(flux_pp_cppflags)  $(xml_pp_cppflags)  $(astro_pp_cppflags)  $(facilities_pp_cppflags)  $(SpectObj_pp_cppflags)  $(GlastPolicy_pp_cppflags)  $(XMLEXT_pp_cppflags)  $(CLHEP_pp_cppflags)  $(cfitsio_pp_cppflags)  $(ROOT_pp_cppflags) 
use_fflags=  $(GRBobs_fflags)  $(flux_fflags)  $(xml_fflags)  $(astro_fflags)  $(facilities_fflags)  $(SpectObj_fflags)  $(GlastPolicy_fflags)  $(XMLEXT_fflags)  $(CLHEP_fflags)  $(cfitsio_fflags)  $(ROOT_fflags) 
use_pp_fflags=  $(GRBobs_pp_fflags)  $(flux_pp_fflags)  $(xml_pp_fflags)  $(astro_pp_fflags)  $(facilities_pp_fflags)  $(SpectObj_pp_fflags)  $(GlastPolicy_pp_fflags)  $(XMLEXT_pp_fflags)  $(CLHEP_pp_fflags)  $(cfitsio_pp_fflags)  $(ROOT_pp_fflags) 
use_linkopts= $(cmt_installarea_linkopts)   $(GRBobs_linkopts)  $(flux_linkopts)  $(xml_linkopts)  $(astro_linkopts)  $(facilities_linkopts)  $(SpectObj_linkopts)  $(GlastPolicy_linkopts)  $(XMLEXT_linkopts)  $(CLHEP_linkopts)  $(cfitsio_linkopts)  $(ROOT_linkopts) 
use_libraries= $(flux_libraries)  $(xml_libraries)  $(astro_libraries)  $(facilities_libraries)  $(SpectObj_libraries)  $(GlastPolicy_libraries)  $(GlastPatternPolicy_libraries)  $(GlastCppPolicy_libraries)  $(XMLEXT_libraries)  $(CLHEP_libraries)  $(cfitsio_libraries)  $(ROOT_libraries) 
includes= $(ppcmd)"$(GRBOBSROOT)" $(use_includes)
fincludes= $(includes)
GRBobs_use_linkopts=  $(GRBobs_linkopts)  $(flux_linkopts)  $(xml_linkopts)  $(astro_linkopts)  $(facilities_linkopts)  $(SpectObj_linkopts)  $(GlastPolicy_linkopts)  $(XMLEXT_linkopts)  $(CLHEP_linkopts)  $(cfitsio_linkopts)  $(ROOT_linkopts) 
test_GRBROOT_use_linkopts=  $(GRBobs_linkopts)  $(flux_linkopts)  $(xml_linkopts)  $(astro_linkopts)  $(facilities_linkopts)  $(SpectObj_linkopts)  $(GlastPolicy_linkopts)  $(XMLEXT_linkopts)  $(CLHEP_linkopts)  $(cfitsio_linkopts)  $(ROOT_linkopts) 
constituents= GRBobs test_GRBROOT 
all_constituents= $(constituents)
constituentsclean= test_GRBROOTclean GRBobsclean 
all_constituentsclean= $(constituentsclean)
cmt_installarea_paths=$(cmt_installarea_prefix)/$(tag)/bin $(cmt_installarea_prefix)/$(tag)/lib $(cmt_installarea_prefix)/share/lib $(cmt_installarea_prefix)/share/bin
cmt_installarea_linkopts= -L/data0/glast/ScienceTools/$(cmt_installarea_prefix)/$(tag)/lib  -L/data0/glast/GRBSimul/$(cmt_installarea_prefix)/$(tag)/lib  -L/data0/glast/GRBSimul/celestialSources/$(cmt_installarea_prefix)/$(tag)/lib 
