# -*- python -*-
# $Id$
# Authors: James Chiang <jchiang@slac.stanford.edu>, Luis Reyes <lreyes@milkyway.gsfc.nasa.gov>
# Version: eblAtten-00-09-00

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

eblAttenLib = libEnv.StaticLibrary('eblAtten', listFiles(['src/*.cxx','src/*.c']))

progEnv.Tool('eblAttenLib')
test_eblAttenBin = progEnv.Program('test_eblAtten', 'src/test/test.cxx')

progEnv.Tool('registerTargets', package = 'eblAtten',
             staticLibraryCxts =  [[eblAttenLib,libEnv]],
             includes = listFiles(['eblAtten/*.h']),
             testAppCxts = [[test_eblAttenBin,progEnv]])
