import glob,os,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

eblAttenLib = libEnv.StaticLibrary('eblAtten', listFiles(['src/*.cxx','src/*.c']))

progEnv.Tool('eblAttenLib')
test_eblAttenBin = progEnv.Program('test_eblAtten', 'src/test/test.cxx')

progEnv.Tool('registerObjects', package = 'eblAtten', libraries =  [eblAttenLib], includes = listFiles(['eblAtten/*.h']), testApps = [test_eblAttenBin])