# -*- python -*-
# $Id$
# Authors: Nicola Omodei<nicola.omodei@pi.infn.it>
# Version: GRBtemplate-01-02-03
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('GRBtemplateLib', depsOnly = 1)
GRBtemplateLib = libEnv.StaticLibrary('GRBtemplate', listFiles(['src/*.cxx']))

progEnv.Tool('GRBtemplateLib')
test_GRBtemplateBin = progEnv.Program('test_GRBtemplate', 'src/test/testGRB.cxx')
test_GRBTEMPLATEROOTBin = progEnv.Program('test_GRBTEMPLATEROOT', 'src/test/other/GRBROOTtest.cxx')

progEnv.Tool('registerObjects', package = 'GRBtemplate', libraries = [GRBtemplateLib], testApps = [test_GRBtemplateBin, test_GRBTEMPLATEROOTBin],
             includes = listFiles(['GRBtemplate/*.h']), data = listFiles(['data/*'], recursive = True), xml = listFiles(['xml/*'], recursive = True))
