CMT_tag=$(tag)
CMTROOT=/afs/slac.stanford.edu/g/glast/applications/CMT/v1r16p20040701
CMT_root=/afs/slac.stanford.edu/g/glast/applications/CMT/v1r16p20040701
CMTVERSION=v1r16p20040701
CMTrelease=15
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/InstallArea/rh9_gcc32/bin:/nfs/farm/g/glast/u05/builds/rh9_gcc32/ScienceTools/ScienceTools-HEAD1.206/InstallArea/rh9_gcc32/bin:/afs/slac.stanford.edu/g/glast/applications/CMT/v1r16p20040701/${CMTBIN}:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/afs/slac.stanford.edu/g/glast/applications/install/@sys/usr/bin:/afs/slac.stanford.edu/g/glast/ground/releases:/afs/slac.stanford.edu/g/glast/ground/scripts:/afs/slac.stanford.edu/g/glast/ground/scripts/ReleaseManager:/nfs/farm/g/glast/u05/GLAST_EXT/rh9_gcc32/ROOT/v3.10.02/root/bin
CLASSPATH=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/InstallArea/share/bin:/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/InstallArea/share/lib:/nfs/farm/g/glast/u05/builds/rh9_gcc32/ScienceTools/ScienceTools-HEAD1.206/InstallArea/share/bin:/nfs/farm/g/glast/u05/builds/rh9_gcc32/ScienceTools/ScienceTools-HEAD1.206/InstallArea/share/lib:/afs/slac.stanford.edu/g/glast/applications/CMT/v1r16p20040701/java
debug_option=-g
cc=gcc
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=flex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -s 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=i686-rhel3-gcc323
DarkMatter_tag=$(tag)
DARKMATTERROOT=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/celestialSources/DarkMatter/v0
DarkMatter_root=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/celestialSources/DarkMatter/v0
DARKMATTERVERSION=v0
DarkMatter_cmtpath=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis
DarkMatter_offset=celestialSources
DarkMatter_project=Project1
CMTINSTALLAREA=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/InstallArea
tag=rh9_gcc32
package=DarkMatter
version=v0
PACKAGE_ROOT=$(DARKMATTERROOT)
srcdir=../src
bin=../$(DarkMatter_tag)/
javabin=../classes/
mgrdir=cmt
project=Project1
use_requirements=requirements $(CMTROOT)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps= $(DarkMatter_stamps) 
use_cflags=  $(DarkMatter_cflags) 
use_pp_cflags=  $(DarkMatter_pp_cflags) 
use_cppflags=  $(DarkMatter_cppflags) 
use_pp_cppflags=  $(DarkMatter_pp_cppflags) 
use_fflags=  $(DarkMatter_fflags) 
use_pp_fflags=  $(DarkMatter_pp_fflags) 
use_linkopts= $(cmt_installarea_linkopts)   $(DarkMatter_linkopts) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
constituents= 
all_constituents= $(constituents)
constituentsclean= 
all_constituentsclean= $(constituentsclean)
cmt_installarea_paths=$(cmt_installarea_prefix)/$(tag)/bin $(cmt_installarea_prefix)/$(tag)/lib $(cmt_installarea_prefix)/share/lib $(cmt_installarea_prefix)/share/bin
Project2_installarea_prefix=$(cmt_installarea_prefix)
Project2_installarea_prefix_remove=$(Project2_installarea_prefix)
LD_LIBRARY_PATH=/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/InstallArea/rh9_gcc32/lib:/nfs/farm/g/glast/u05/builds/rh9_gcc32/ScienceTools/ScienceTools-HEAD1.206/InstallArea/rh9_gcc32/lib:/nfs/farm/g/glast/u05/GLAST_EXT/rh9_gcc32/cfitsio/v2470/lib:/nfs/farm/g/glast/u05/GLAST_EXT/rh9_gcc32/CLHEP/1.8.0.0/lib:/nfs/farm/g/glast/u05/GLAST_EXT/rh9_gcc32/ROOT/v3.10.02/root/bin:/nfs/farm/g/glast/u05/GLAST_EXT/rh9_gcc32/ROOT/v3.10.02/root/lib:/nfs/farm/g/glast/u05/GLAST_EXT/rh9_gcc32/xerces/1.7.0/lib:/nfs/farm/g/glast/u05/builds/rh9_gcc32/ScienceTools/ScienceTools-HEAD1.206/xml/v4r11p1/rh9_gcc32
Project1_installarea_prefix=$(cmt_installarea_prefix)
Project1_installarea_prefix_remove=$(Project1_installarea_prefix)
cmt_installarea_linkopts= -L/nfs/slac/g/glast/users/glground/cohen/GRBAnalysis/$(Project1_installarea_prefix)/$(tag)/lib  -L/nfs/farm/g/glast/u05/builds/rh9_gcc32/ScienceTools/ScienceTools-HEAD1.206/$(Project2_installarea_prefix)/$(tag)/lib 
