# -*- python -*-
# $Id$
# Authors: Nicola Omodei<nicola.omodei@pi.infn.it>
# Version: SpectObj-01-03-05
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('SpectObjLib', depsOnly = 1)
SpectObjLib = libEnv.StaticLibrary('SpectObj', listFiles(['src/*.cxx']))

progEnv.Tool('registerObjects', package = 'SpectObj', libraries = [SpectObjLib], includes = listFiles(['SpectObj/*.h']), data = listFiles(['data/*'], recursive = True))
