# -*- python -*-
# $Id$
# Authors: Nicola Omodei<nicola.omodei@pi.infn.it>
# Version: GRBobs-03-03-02

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('GRBobsLib', depsOnly = 1)
GRBobsLib = libEnv.StaticLibrary('GRBobs', listFiles(['src/*.cxx', 'src/GRBobs/*.cxx']))

progEnv.Tool('GRBobsLib')
test_GRBobsBin = progEnv.Program('test_GRBobs', 'src/test/testGRB.cxx')
test_GRBobsROOTBin = progEnv.Program('test_GRBobsROOT', 'src/test/other/GRBROOTtest.cxx')

progEnv.Tool('registerObjects', package = 'GRBobs', libraries = [GRBobsLib], testApps = [test_GRBobsBin, test_GRBobsROOTBin], includes = listFiles(['GRBobs/*.h']),
             data = listFiles(['data/*'], recursive = True), xml = listFiles(['xml/*'], recursive = True))
