# -*- python -*-
# $Id$
# Authors: Richard Dubois<richard@slac.stanford.edu>
# Version: microQuasar-01-04-02
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('microQuasarLib', depsOnly = 1)
microQuasarLib = libEnv.Library('microQuasar', listFiles(['src/*.cxx']))

progEnv.Tool('microQuasarLib')
test_microQuasar = progEnv.Program('test_microQuasar', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'microQuasar', libraries = [microQuasarLib], includes = listFiles(['microQuasar/*.h']), testApps = [test_microQuasar],
             xml = listFiles(['xml/*'], recursive = True))
