import glob,os,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

microQuasarLib = libEnv.Library('microQuasar', listFiles(['src/*.cxx']))

progEnv.Tool('microQuasarLib')
test_microQuasar = progEnv.Program('test_microQuasar', listFiles(['src/test/*.cxx']))

progEnv.Tool('registerObjects', package = 'microQuasar', libraries = [microQuasarLib], includes = listFiles(['microQuasar/*.h']), testApps = [test_microQuasar])