# -*- python -*-
# $Id$
# Authors: Nicola Omodei<nicola.omodei@pi.infn.it>, Massimiliano Razzano <massimiliano.razzano@pi.infn.it>
# Version: Pulsar-02-05-01
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('PulsarLib', depsOnly = 1)
PulsarLib = libEnv.StaticLibrary('Pulsar', listFiles(['src/*.cxx', 'src/Pulsar/*.cxx']))

progEnv.Tool('PulsarLib')
test_PulsarROOTBin = progEnv.Program('test_PulsarROOT', 'src/test/other/PulsarROOTtest.cxx')

progEnv.Tool('registerObjects', package = 'Pulsar', libraries = [PulsarLib], includes = listFiles(['Pulsar/*.h']), testApps = [test_PulsarROOTBin],
             data = listFiles(['data/*'], recursive = True), xml = listFiles(['xml/*'], recursive = True))
