import glob,os,platform

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

PulsarLib = libEnv.StaticLibrary('Pulsar', listFiles(['src/*.cxx', 'src/Pulsar/*.cxx']))

progEnv.Tool('PulsarLib')
test_PulsarROOTBin = progEnv.Program('test_PulsarROOT', 'src/test/other/PulsarROOTtest.cxx')

progEnv.Tool('registerObjects', package = 'Pulsar', libraries = [PulsarLib], includes = listFiles(['Pulsar/*.h']), testApps = [test_PulsarROOTBin])
