/*!
* \class LatGrb
*
* \brief This class is intended to be instantiataed by the GRBmaker::create method.
* \author Jay Norris        jnorris@lheapop.gsfc.nasa.gov
* \author Sandhia Bansal    sandhiab@lheapop.gsfc.nasa.gov
*
*
* This class provides methods to create LAT photon lists in (optionally) specified
* directory.  Alternatively, if the file was generated by a previous run, it can read
* that file and provide data for the simulation.
*/


#ifndef LAT_GRB_H
#define LAT_GRB_H

#include <vector>
#include <string>

#include "GRBurst.h"

class HepRandomEngine;



class LatGrb  : public GRBurst
{
public:
     /*!
      * \brief Constructor.
      */
    LatGrb(HepRandomEngine *engine, const std::string &prefix, 
        const std::string &dir=0);
    
     /*!
      * \brief Constructor.
      */
    LatGrb(HepRandomEngine *engine, const double duration, const int npuls, 
        const double flux, const double fraction, const double alpha, 
        const double beta, const double epeak, const double specnorm, 
        const bool flag);
    
     /*!
      * \brief Destructor.
      */
    virtual ~LatGrb()   {};
    
    
    
    // Accessors
    static double emax()    { return s_emax; }
    
private:
    /*!
    * \brief Compute spectral normalization.
    *
    * SpecNorm units, integrated Peak Flux:  photons cm^-2 s^-1 (> Ethres).  Researches on normalization:
    *   (1) J.T. Bonnell's fits to bright BATSE bursts; 
    *   (2) comparison with EGRET norms for bright bursts - Catelli's, Dingus' and Schneid's works; and definitively 
    *   (3) analysis of Preece et al. (ApJS 2000, 126, 19) spectroscopy catalog of bright BATSE bursts 
    *		using IDL routine Specanal.pro.
    * The cofactors for N_inc, the number of photons incident on the 6-meter diameter circle are:
    *   (a) {average flux / peak flux} =~ 1/7;
    *   (b) scaling by (peak_flux)^1.5, determined from inspection of Preece et al.;
    *   (c) duration (seconds);
    *   (d) 282743 cm^2 (6-meter dia. illuminated disk);
    *   (e) scaling to integral above Ethres (e.g., 0.03 GeV) for case beta = -2;
    *   (f) dispersion (dynamic range) to approximately replicate the scatter in peak flux
    *		vs. normalization at 1 MeV as estimated from Preece et al. catalog; and
    *   (g) a dependence on power-law index as estimated from Preece et al. catalog.
    *
    * Thus, the number of photons produced is consistent with normally incident flux on the projected disk 
    * of the GLAST illumination sphere, integrated above Ethres, for chosen peak flux and duration,  
    * with the photon energies distributed as a power-law.
    *
    * Some of these cofactors are applied in LatGrb::specnorm; the remaining ones 
    * are applied in LatGrb::nphoton, which follows this module.
    */
    void calcSpecnorm(HepRandomEngine *engine);

    /*!
    * \brief Calculate number of photons generated by the current burst.
    */
    virtual long calcNphoton(HepRandomEngine *engine, long isim =0);
    
    /*!
     * \brief Compute photon energies for the current burst.
     */
    void makeEnergies(HepRandomEngine *engine);
    
    /*! 
     * \brief Generate burst data
     */
    virtual void makeGRB(HepRandomEngine *engine, bool first);
    
    

    // Data Members
    static const double  s_emax;
};

#endif // LAT_GRB_H
