# -*- python -*-
# $Id$
# Authors: Nicola Omodei<nicola.omodei@pi.infn.it>
# Version: GRB-04-04-04
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('GRBLib', depsOnly = 1)
GRBLib = libEnv.StaticLibrary('GRB', listFiles(['src/GRB/*.cxx', 'src/*.cxx']))

progEnv.Tool('GRBLib')
test_GRBROOTBin = progEnv.Program('test_GRBROOT', listFiles(['src/test/other/GRBROOTtest.cxx']))

progEnv.Tool('registerTargets', package = 'GRB',
             staticLibraryCxts = [[GRBLib,libEnv]],
             testAppCxts = [[test_GRBROOTBin, progEnv]],
             data = listFiles(['data/*'], recursive = True),
             xml = listFiles(['xml/*'], recursive = True))
