#$Id$
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('GRBLib', depsOnly = 1)
GRBLib = libEnv.StaticLibrary('GRB', listFiles(['src/GRB/*.cxx', 'src/*.cxx']))

progEnv.Tool('GRBLib')
test_GRBROOTBin = progEnv.Program('test_GRBROOT', listFiles(['src/test/other/GRBROOTtest.cxx']))

progEnv.Tool('registerObjects', package = 'GRB', libraries = [GRBLib], testApps = [test_GRBROOTBin])
